### ISSUE TITLE
New `PositiveInt` type

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/libraries#82]
## Description

Introduce a new `PositiveInt` type in the `kotools.types` package having the same feature of the `kotools.types.number.PositiveInt` type.

The final design for explicit integers in Kotools Types 4.0.0 could look like the following:

```kotlin
import kotlin.jvm.JvmInline

sealed interface ExplicitInt {
    val value: Int
}

@JvmInline value class NonZeroInt(override val value: Int) : ExplicitInt
@JvmInline value class PositiveInt(override val value: Int) : ExplicitInt
@JvmInline value class StrictlyPositiveInt(override val value: Int) : ExplicitInt
@JvmInline value class NegativeInt(override val value: Int) : ExplicitInt
@JvmInline value class StrictlyNegativeInt(override val value: Int) : ExplicitInt
```

## Checklist

- [x] Add the `kotools.types.PositiveInt` type and its primary builder.
- [x] Add unary operations to the new type (implemented by #88).
- [ ] Add binary operations to the new type (fixed by #93).
- [x] Make the new type serializable.
- [ ] Deprecate the `kotools.types.number.PositiveInt` type (fixed by #94).
- [x] Update `Work in progress` section in changelog.

**Comment by LVMVRQUXL** [comment]
Here's a hint of the binary operations dedicated to this new type:
```kotlin
import kotools.types.NegativeInt
import kotools.types.NonZeroInt
import kotools.types.PositiveInt
import kotools.types.StrictlyPositiveInt
import kotools.types.StrictlyNegativeInt

public operator fun PositiveInt.div(other: StrictlyPositiveInt): PositiveInt = TODO()
public operator fun PositiveInt.div(other: StrictlyNegativeInt): NegativeInt = TODO()

public operator fun PositiveInt.rem(other: NonZeroInt): PositiveInt = TODO()
public operator fun PositiveInt.rem(other: StrictlyPositiveInt): PositiveInt = TODO()
public operator fun PositiveInt.rem(other: StrictlyNegativeInt): PositiveInt = TODO()
```

**Comment by LVMVRQUXL** [comment]
Convert its member functions to extensions.

**Comment by LVMVRQUXL** [comment]
Done.
