### ISSUE TITLE
New `StrictlyPositiveInt` type

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/libraries#83]
## Description

Introduce a new `StrictlyPositiveInt` type in the `kotools.types` package having the same feature of the `kotools.types.number.StrictlyPositiveInt` type.

The final design for explicit integers in Kotools Types 4.0.0 could look like the following:

```kotlin
import kotlin.jvm.JvmInline

sealed interface ExplicitInt {
    val value: Int
}

@JvmInline value class NonZeroInt(override val value: Int) : ExplicitInt
@JvmInline value class PositiveInt(override val value: Int) : ExplicitInt
@JvmInline value class StrictlyPositiveInt(override val value: Int) : ExplicitInt
@JvmInline value class NegativeInt(override val value: Int) : ExplicitInt
@JvmInline value class StrictlyNegativeInt(override val value: Int) : ExplicitInt
```

## Checklist

- [x] Add the `kotools.types.StrictlyPositiveInt` type and its primary builder.
- [x] Add conversions to the new type (implemented by #87).
- [x] Add unary operations to the new type (implemented by #88).
- [x] Add binary operations to the new type (fixed by #100).
- [x] Make the new type serializable.
- [x] Deprecate the `kotools.types.number.StrictlyPositiveInt` type (fixed by #102).
- [x] Update `Work in progress` section in changelog.

**Comment by LVMVRQUXL** [comment]
See [this Kotlin playground](https://pl.kotl.in/-aJPIAk4Z) for more hints about the types returned by the binary operations of this new `StrictlyPositiveInt` type.

**Comment by LVMVRQUXL** [comment]
Convert its member functions to extensions.

**Comment by LVMVRQUXL** [comment]
Done.
