### ISSUE TITLE
New `StrictlyNegativeInt` type

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/libraries#85]
## Description

Introduce a new `StrictlyNegativeInt` type in the `kotools.types` package having the same feature of the `kotools.types.number.StrictlyNegativeInt` type.

The final design for explicit integers in Kotools Types 4.0.0 could look like the following:

```kotlin
import kotlin.jvm.JvmInline

sealed interface ExplicitInt {
    val value: Int
}

@JvmInline value class NonZeroInt(override val value: Int) : ExplicitInt
@JvmInline value class PositiveInt(override val value: Int) : ExplicitInt
@JvmInline value class StrictlyPositiveInt(override val value: Int) : ExplicitInt
@JvmInline value class NegativeInt(override val value: Int) : ExplicitInt
@JvmInline value class StrictlyNegativeInt(override val value: Int) : ExplicitInt
```

## Checklist

- [x] Add the `kotools.types.StrictlyNegativeInt` type and its primary builder.
- [x] Add conversions to the new type (implemented by #87).
- [x] Add unary operations to the new type (implemented by #88).
- [x] Add binary operations to the new type (fixed by #101).
- [ ] Make the new type serializable.
- [ ] Deprecate the `kotools.types.number.StrictlyNegativeInt` type.
- [ ] Update `Work in progress` section in changelog.

**Comment by LVMVRQUXL** [comment]
Convert its member functions to extensions.
